export const injectedMovies = {
  "now-playing": [
    {
      adult: false,
      backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
      genre_ids: (4)[(12, 14, 35, 28)],
      id: 451048,
      original_language: "en",
      original_title: "Jungle Cruise",
      overview:
        "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
      popularity: 4386.523,
      poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
      release_date: "2021-07-28",
      title: "Jungle Cruise",
      video: false,
      vote_average: 7.9,
      vote_count: 1983,
    },
  ],
  "top-rated": [
    {
      adult: false,
      backdrop_path: "/las0P4Dua54XrZ73VQmGUaH1z0U.jpg",
      genre_ids: (4)[(16, 28, 18, 878)],
      id: 283566,
      original_language: "ja",
      original_title: "シン・エヴァンゲリオン劇場版:||",
      overview:
        "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
      popularity: 359.904,
      poster_path: "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
      release_date: "2021-03-08",
      title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
      video: false,
      vote_average: 8.8,
      vote_count: 231,
    },
    {
      adult: false,
      backdrop_path: "/las0P4Dua54XrZ73VQmGUaH1z0U.jpg",
      genre_ids: (4)[(16, 28, 18, 878)],
      id: 283566,
      original_language: "ja",
      original_title: "シン・エヴァンゲリオン劇場版:||",
      overview:
        "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
      popularity: 359.904,
      poster_path: "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
      release_date: "2021-03-08",
      title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
      video: false,
      vote_average: 8.8,
      vote_count: 231,
    },
    {
      adult: false,
      backdrop_path: "/las0P4Dua54XrZ73VQmGUaH1z0U.jpg",
      genre_ids: (4)[(16, 28, 18, 878)],
      id: 283566,
      original_language: "ja",
      original_title: "シン・エヴァンゲリオン劇場版:||",
      overview:
        "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
      popularity: 359.904,
      poster_path: "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
      release_date: "2021-03-08",
      title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
      video: false,
      vote_average: 8.8,
      vote_count: 231,
    },
  ],

  trending: [
    {
      adult: false,
      backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
      genre_ids: (4)[(12, 14, 35, 28)],
      id: 451048,
      original_language: "en",
      original_title: "Jungle Cruise",
      overview:
        "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
      popularity: 4386.523,
      poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
      release_date: "2021-07-28",
      title: "Jungle Cruise",
      video: false,
      vote_average: 7.9,
      vote_count: 1983,
    },
    {
      adult: false,
      backdrop_path: "/las0P4Dua54XrZ73VQmGUaH1z0U.jpg",
      genre_ids: (4)[(16, 28, 18, 878)],
      id: 283566,
      original_language: "ja",
      original_title: "シン・エヴァンゲリオン劇場版:||",
      overview:
        "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
      popularity: 359.904,
      poster_path: "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
      release_date: "2021-03-08",
      title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
      video: false,
      vote_average: 8.8,
      vote_count: 231,
    },
    {
      adult: false,
      backdrop_path: "/las0P4Dua54XrZ73VQmGUaH1z0U.jpg",
      genre_ids: (4)[(16, 28, 18, 878)],
      id: 283566,
      original_language: "ja",
      original_title: "シン・エヴァンゲリオン劇場版:||",
      overview:
        "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
      popularity: 359.904,
      poster_path: "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
      release_date: "2021-03-08",
      title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
      video: false,
      vote_average: 8.8,
      vote_count: 231,
    },
  ],
};
